### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [zmthy/grace-tmbundle#1]
I would like to use your grammar for Grace but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by zmthy** [comment]
Thanks for pointing this out. The project is now licensed under GPLv3+.

**Comment by pchaigno** [comment]
Thanks!

**Comment by pchaigno** [comment]
@zmthy Your grammar is now used to highlight Grace code on GitHub (files and code snippets in Markdown documents)! (See github/linguist#2071 for more information.)

**Comment by zmthy** [comment]
Great, this has helped me find some mistakes (I don't actually use this highlighting personally), and I've tidied up the syntax groups to get better colouring on Github. Looking forward to the next update.

**Comment by pchaigno** [comment]
Great!

> Looking forward to the next update.

It usually happens every couple weeks with the next release.
