### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [zmthy/grace-tmbundle#2]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by zmthy** [comment]
I realised this a while after applying the GPL license, but never followed up on whether Linguist (and potentially Sublime and Atom) was improperly using this software. I GPL by default but I'm not particularly fussed about it for a package like this. As the sole contributor to the software, I've re-licensed to MIT and pushed a new release 2.0.0.

**Comment by arfon** [comment]
Many thanks!
